#!/usr/bin/env bash

flatpak remote-delete --force fedora

flatpak install --noninteractive --assumeyes \
	io.github.fabrialberio.pinapp \
	net.nokyan.Resources \
	org.gnome.Calculator \
	org.gnome.Loupe \
	org.gnome.NautilusPreviewer \
	org.mozilla.firefox \
	page.tesk.Refine \
	com.github.tchx84.Flatseal \
	io.github.zaedus.spider
